# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(1020, 500)
        AdminWindow.setMinimumSize(QtCore.QSize(1020, 500))
        AdminWindow.setMaximumSize(QtCore.QSize(1020, 500))
        self.centralwidget = QtWidgets.QWidget(AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 991, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.catalog_frame = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.catalog_frame.setContentsMargins(0, 0, 0, 0)
        self.catalog_frame.setObjectName("catalog_frame")
        self.search_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_edit.setGeometry(QtCore.QRect(10, 10, 931, 31))
        self.search_edit.setStyleSheet("padding-left: 10px;")
        self.search_edit.setObjectName("search_edit")
        self.reload = QtWidgets.QPushButton(self.centralwidget)
        self.reload.setGeometry(QtCore.QRect(950, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reload.setFont(font)
        self.reload.setObjectName("reload")
        AdminWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(AdminWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1020, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        AdminWindow.setMenuBar(self.menuBar)
        self.add_employee = QtWidgets.QAction(AdminWindow)
        self.add_employee.setObjectName("add_employee")
        self.add_product = QtWidgets.QAction(AdminWindow)
        self.add_product.setObjectName("add_product")
        self.add_category = QtWidgets.QAction(AdminWindow)
        self.add_category.setObjectName("add_category")
        self.edit_status_employee = QtWidgets.QAction(AdminWindow)
        self.edit_status_employee.setObjectName("edit_status_employee")
        self.export_report = QtWidgets.QAction(AdminWindow)
        self.export_report.setObjectName("export_report")
        self.menu.addAction(self.add_employee)
        self.menu.addAction(self.add_product)
        self.menu.addAction(self.add_category)
        self.menu_2.addAction(self.edit_status_employee)
        self.menu_3.addAction(self.export_report)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Панель администратора"))
        self.search_edit.setPlaceholderText(_translate("AdminWindow", "Поиск товара"))
        self.reload.setText(_translate("AdminWindow", "↺"))
        self.menu.setTitle(_translate("AdminWindow", "Добавить"))
        self.menu_2.setTitle(_translate("AdminWindow", "Изменить"))
        self.menu_3.setTitle(_translate("AdminWindow", "Прочее"))
        self.add_employee.setText(_translate("AdminWindow", "Сотрудник"))
        self.add_product.setText(_translate("AdminWindow", "Товар"))
        self.add_category.setText(_translate("AdminWindow", "Категория"))
        self.edit_status_employee.setText(_translate("AdminWindow", "Статус сотрудника"))
        self.export_report.setText(_translate("AdminWindow", "Экспорт отчета"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminWindow()
    ui.setupUi(AdminWindow)
    AdminWindow.show()
    sys.exit(app.exec_())
