# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog/edit_product_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditProduct(object):
    def setupUi(self, EditProduct):
        EditProduct.setObjectName("EditProduct")
        EditProduct.resize(557, 443)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditProduct)
        self.buttonBox.setGeometry(QtCore.QRect(190, 390, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.title = QtWidgets.QLabel(EditProduct)
        self.title.setGeometry(QtCore.QRect(20, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.groupBox = QtWidgets.QGroupBox(EditProduct)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 531, 301))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 101, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.type_change = QtWidgets.QComboBox(self.groupBox)
        self.type_change.setGeometry(QtCore.QRect(140, 30, 231, 22))
        self.type_change.setObjectName("type_change")
        self.on_sale = QtWidgets.QRadioButton(self.groupBox)
        self.on_sale.setGeometry(QtCore.QRect(390, 30, 95, 20))
        self.on_sale.setObjectName("on_sale")
        self.comment = QtWidgets.QTextEdit(self.groupBox)
        self.comment.setGeometry(QtCore.QRect(20, 70, 491, 201))
        self.comment.setObjectName("comment")

        self.retranslateUi(EditProduct)
        self.buttonBox.accepted.connect(EditProduct.accept) # type: ignore
        self.buttonBox.rejected.connect(EditProduct.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditProduct)

    def retranslateUi(self, EditProduct):
        _translate = QtCore.QCoreApplication.translate
        EditProduct.setWindowTitle(_translate("EditProduct", "Dialog"))
        self.title.setText(_translate("EditProduct", "Название продукта"))
        self.groupBox.setTitle(_translate("EditProduct", "Инвентаризация"))
        self.lineEdit.setPlaceholderText(_translate("EditProduct", "Количество"))
        self.on_sale.setText(_translate("EditProduct", "В продаже"))
        self.comment.setPlaceholderText(_translate("EditProduct", "Комментарий"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditProduct = QtWidgets.QDialog()
    ui = Ui_EditProduct()
    ui.setupUi(EditProduct)
    EditProduct.show()
    sys.exit(app.exec_())
