# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog/export_report_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportReport(object):
    def setupUi(self, ExportReport):
        ExportReport.setObjectName("ExportReport")
        ExportReport.resize(400, 201)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExportReport)
        self.buttonBox.setGeometry(QtCore.QRect(50, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.path_file = QtWidgets.QLineEdit(ExportReport)
        self.path_file.setGeometry(QtCore.QRect(10, 20, 331, 31))
        self.path_file.setObjectName("path_file")
        self.get_path_file = QtWidgets.QPushButton(ExportReport)
        self.get_path_file.setGeometry(QtCore.QRect(350, 20, 41, 28))
        self.get_path_file.setObjectName("get_path_file")
        self.groupBox = QtWidgets.QGroupBox(ExportReport)
        self.groupBox.setGeometry(QtCore.QRect(230, 70, 161, 61))
        self.groupBox.setObjectName("groupBox")
        self.is_csv = QtWidgets.QRadioButton(self.groupBox)
        self.is_csv.setGeometry(QtCore.QRect(20, 30, 95, 20))
        self.is_csv.setChecked(True)
        self.is_csv.setObjectName("is_csv")
        self.is_xls = QtWidgets.QRadioButton(self.groupBox)
        self.is_xls.setGeometry(QtCore.QRect(90, 30, 51, 20))
        self.is_xls.setObjectName("is_xls")
        self.groupBox_2 = QtWidgets.QGroupBox(ExportReport)
        self.groupBox_2.setGeometry(QtCore.QRect(19, 70, 201, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.is_sales = QtWidgets.QRadioButton(self.groupBox_2)
        self.is_sales.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.is_sales.setChecked(True)
        self.is_sales.setObjectName("is_sales")
        self.is_changes = QtWidgets.QRadioButton(self.groupBox_2)
        self.is_changes.setGeometry(QtCore.QRect(100, 30, 95, 20))
        self.is_changes.setObjectName("is_changes")

        self.retranslateUi(ExportReport)
        self.buttonBox.accepted.connect(ExportReport.accept) # type: ignore
        self.buttonBox.rejected.connect(ExportReport.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExportReport)

    def retranslateUi(self, ExportReport):
        _translate = QtCore.QCoreApplication.translate
        ExportReport.setWindowTitle(_translate("ExportReport", "Сформировать отчет"))
        self.path_file.setPlaceholderText(_translate("ExportReport", "Путь до файла"))
        self.get_path_file.setText(_translate("ExportReport", "📁"))
        self.groupBox.setTitle(_translate("ExportReport", "Тип файла"))
        self.is_csv.setText(_translate("ExportReport", "csv"))
        self.is_xls.setText(_translate("ExportReport", "xls"))
        self.groupBox_2.setTitle(_translate("ExportReport", "Тип отчета"))
        self.is_sales.setText(_translate("ExportReport", "продажи"))
        self.is_changes.setText(_translate("ExportReport", "изменения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExportReport = QtWidgets.QDialog()
    ui = Ui_ExportReport()
    ui.setupUi(ExportReport)
    ExportReport.show()
    sys.exit(app.exec_())
