# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog/new_employee_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewEmployee(object):
    def setupUi(self, NewEmployee):
        NewEmployee.setObjectName("NewEmployee")
        NewEmployee.resize(433, 249)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewEmployee)
        self.buttonBox.setGeometry(QtCore.QRect(200, 190, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.login = QtWidgets.QLineEdit(NewEmployee)
        self.login.setGeometry(QtCore.QRect(30, 40, 371, 31))
        self.login.setObjectName("login")
        self.full_name = QtWidgets.QLineEdit(NewEmployee)
        self.full_name.setGeometry(QtCore.QRect(30, 90, 371, 31))
        self.full_name.setObjectName("full_name")
        self.password = QtWidgets.QLineEdit(NewEmployee)
        self.password.setGeometry(QtCore.QRect(30, 140, 371, 31))
        self.password.setObjectName("password")

        self.retranslateUi(NewEmployee)
        self.buttonBox.accepted.connect(NewEmployee.accept) # type: ignore
        self.buttonBox.rejected.connect(NewEmployee.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewEmployee)

    def retranslateUi(self, NewEmployee):
        _translate = QtCore.QCoreApplication.translate
        NewEmployee.setWindowTitle(_translate("NewEmployee", "Новый сотрудник"))
        self.login.setPlaceholderText(_translate("NewEmployee", "Логин"))
        self.full_name.setPlaceholderText(_translate("NewEmployee", "ФИО"))
        self.password.setPlaceholderText(_translate("NewEmployee", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewEmployee = QtWidgets.QDialog()
    ui = Ui_NewEmployee()
    ui.setupUi(NewEmployee)
    NewEmployee.show()
    sys.exit(app.exec_())
