# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog/new_product_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewProduct(object):
    def setupUi(self, NewProduct):
        NewProduct.setObjectName("NewProduct")
        NewProduct.resize(435, 230)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewProduct)
        self.buttonBox.setGeometry(QtCore.QRect(60, 170, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.price = QtWidgets.QLineEdit(NewProduct)
        self.price.setGeometry(QtCore.QRect(30, 120, 121, 31))
        self.price.setAlignment(QtCore.Qt.AlignCenter)
        self.price.setObjectName("price")
        self.barcode = QtWidgets.QLineEdit(NewProduct)
        self.barcode.setGeometry(QtCore.QRect(30, 70, 371, 31))
        self.barcode.setInputMask("")
        self.barcode.setObjectName("barcode")
        self.product_name = QtWidgets.QLineEdit(NewProduct)
        self.product_name.setGeometry(QtCore.QRect(30, 20, 371, 31))
        self.product_name.setObjectName("product_name")
        self.category = QtWidgets.QComboBox(NewProduct)
        self.category.setGeometry(QtCore.QRect(160, 120, 241, 31))
        self.category.setObjectName("category")

        self.retranslateUi(NewProduct)
        self.buttonBox.accepted.connect(NewProduct.accept) # type: ignore
        self.buttonBox.rejected.connect(NewProduct.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewProduct)

    def retranslateUi(self, NewProduct):
        _translate = QtCore.QCoreApplication.translate
        NewProduct.setWindowTitle(_translate("NewProduct", "Новый товар"))
        self.price.setPlaceholderText(_translate("NewProduct", "Цена"))
        self.barcode.setPlaceholderText(_translate("NewProduct", "Номер штрихкода"))
        self.product_name.setPlaceholderText(_translate("NewProduct", "Название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewProduct = QtWidgets.QDialog()
    ui = Ui_NewProduct()
    ui.setupUi(NewProduct)
    NewProduct.show()
    sys.exit(app.exec_())
