# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(500, 300)
        AuthWindow.setMinimumSize(QtCore.QSize(500, 300))
        AuthWindow.setMaximumSize(QtCore.QSize(500, 300))
        AuthWindow.setStyleSheet("background-color: #fff;\n"
"")
        self.centralwidget = QtWidgets.QWidget(AuthWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.login_edit.setGeometry(QtCore.QRect(50, 110, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_edit.setFont(font)
        self.login_edit.setStyleSheet("padding: 0 5px 0 5px;")
        self.login_edit.setObjectName("login_edit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 500, 38))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #664986;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_edit.setGeometry(QtCore.QRect(50, 160, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("padding: 0 5px 0 5px;")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.auth_btn = QtWidgets.QPushButton(self.centralwidget)
        self.auth_btn.setGeometry(QtCore.QRect(185, 210, 130, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.auth_btn.setFont(font)
        self.auth_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.auth_btn.setAutoFillBackground(False)
        self.auth_btn.setStyleSheet("background-color: #60467e;\n"
"color: #fff;\n"
"border-radius: 10px;")
        self.auth_btn.setCheckable(True)
        self.auth_btn.setObjectName("auth_btn")
        AuthWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Авторизация"))
        self.login_edit.setPlaceholderText(_translate("AuthWindow", "Логин"))
        self.label.setText(_translate("AuthWindow", "Авторизация"))
        self.password_edit.setPlaceholderText(_translate("AuthWindow", "Пароль"))
        self.auth_btn.setText(_translate("AuthWindow", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthWindow = QtWidgets.QMainWindow()
    ui = Ui_AuthWindow()
    ui.setupUi(AuthWindow)
    AuthWindow.show()
    sys.exit(app.exec_())
